services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
    networks:
      - emergevision-network

  # Development frontend (with hot reload)
  frontend-dev:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    # This command is added to tell the React dev server to listen on all network interfaces.
    command: npm start -- --host 0.0.0.0
    networks:
      - emergevision-network

  # Production frontend (optimized build)
  frontend-prod:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - emergevision-network

networks:
  emergevision-network:
    driver: bridge
